baseURL = "https://blog.notifyer.xyz"
title = "Hugo Start"
paginate = 5.0
theme = "PaperMod"
languageCode = "zh"
DefaultContentLanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
enableGitInfo = false
googleAnalytics = ""
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Hugo Start"
description = "Hugo Start with PaperMod"
author = "Your Name"
images = [
  "opengraph.webp"
]
DateFormat = "2006-01-02"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Hugo Start"
  icon = "/apple-touch-icon.png"
  iconHeight = 35.0

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120.0
  imageHeight = 120.0
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to hugo start, this is a example of Hugo and PaperMod"

  [params.analytics]

    [params.analytics.google]
    SiteVerificationTag = ""

    [params.analytics.bing]
    SiteVerificationTag = ""

    [params.analytics.yandex]
    SiteVerificationTag = ""

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/DejavuMoe/hugo-start/edit/master/content/posts"
  Text = "Edit on GitHub"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0.0
  distance = 1000.0
  threshold = 0.4
  minMatchCharLength = 0.0
  keys = [
    "title",
    "permalink",
    "summary",
    "content"
  ]

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/DejavuMoe/hugo-start"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://sink.love/@dejavu"

[menu]

  [[menu.main]]
  identifier = "首页"
  name = "首页"
  url = "/"
  weight = 1.0

  [[menu.main]]
  identifier = "分类"
  name = "分类"
  url = "/categories/"
  weight = 10.0

  [[menu.main]]
  identifier = "标签"
  name = "标签"
  url = "/tags/"
  weight = 20.0

  [[menu.main]]
  identifier = "仓库"
  name = "仓库"
  url = "https://github.com/DejavuMoe/hugo-start"
  weight = 30.0

[markup]

  [markup.highlight]
  noClasses = false

[privacy]

  [privacy.vimeo]
  disabled = true
  enableDNT = true
  simple = true

  [privacy.twitter]
  disabled = true
  enableDNT = true
  simple = true

  [privacy.instagram]
  disabled = true
  simple = true

  [privacy.youtube]
  disabled = true
  privacyEnhanced = true

[services]

  [services.instagram]
  disableInlineCSS = true

  [services.twitter]
  disableInlineCSS = true